#!/bin/bash -ex

# clean
rm -rf *.mod *.o *.lst *.x

# use gftl lib or local
use_gftl=false   # internal gftl library
#use_gftl=true   # external gftl library

#mach='x86_64'
mach=${1:-'fx1000'}

if [[ $mach == 'fx1000' ]] ; then
  comp="frt -Ec -Nlst=a,lst=d,lst=i,lst=p,lst=t,lst=x -Nalloc_assign -Cpp"
  lib_path='hpc_stack/fujitsu-1.2.33'
  gftl_lib=/users/xb80/opt/${lib_path}/gftl-shared/v1.3.0
elif [[ $mach == 'x86_64' ]] ; then
  comp="gfortran -Wall -std=gnu -fbacktrace -cpp"
  gftl_lib=/users/xb80/opt/${mach}/gftl-shared-1.3.0
fi

if $use_gftl ; then
  include="-I${gftl_lib}/GFTL_SHARED-1.3/include/v1 -I${gftl_lib}/GFTL-1.4/include/v1"
  lib="${gftl_lib}/GFTL_SHARED-1.3/lib/libgftl-shared-v1.a"
fi

# compile
${comp} ${include} -c String.F90
${comp} ${include} -c ArrayWrapper.F90
$use_gftl || ${comp} ${include} -c UnlimitedVector.cpp.f90
${comp} ${include} -c UnlimitedUtilities.F90 
${comp} ${include} -c main.f90 

# link
${comp} *.o ${lib} -o main_${mach}.x

# test
./main_${mach}.x

